server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #启动时执行初始化脚本schema-*.sql、data-*.sql
    #星号为配置的spring.datasource.platform，默认为"all"。即，如果想要在项目启动时创建表，则在类路径下创建文件 schema-all.sql，编写建表语句。
    #也可以使用spring.datasource.schema配置要执行的初始化ddl路径（可以用数组形式配置多个文件）:
    #使用spring.datasource.data配置要执行的数据运行脚本
    #initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource

    # Druid其他配置
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1 from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true

    # 配置Druid后台监控
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
druid:
  stat:
    view-servlet:
      # 具体配置项参考ServletRegistrationBean。 可以配置的值参考StatViewServlet
      initParameters: {loginUsername: admin, loginPassword: 123456, allow: }
    web-filter:
      # 具体配置项参考FilterRegistrationBean
      initParameters: {exclusions: '*.js,*.css,/druid/*'}
      urlPatterns: /*